name: Export and Upload Resume

on:
  push:
    paths:
      - 'resume.html'
      - '.github/workflows/deploy-resume.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Export HTML to PDF
        run: |
          node -e "
            const puppeteer = require('puppeteer');
            const fs = require('fs');
            (async () => {
              const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
              const page = await browser.newPage();
              const html = fs.readFileSync('index.html', 'utf8');
              await page.setContent(html, { waitUntil: 'networkidle0' });
              await page.pdf({ path: 'resume.pdf', format: 'A4' });
              await browser.close();
            })();
          "

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 cp resume.pdf s3://vickyops-bucket/Vicky-Resume.pdf 
